%% Project: Two River System model

% April 14. 2015
%% creating a function that inputs season(as number) and computes revenue, maxpower, and the corresponding flowrates of A and B at Maxpower
function [revenue,maxpower,corrflowAB] = Projectfinal(season)
close all
% Two dams control the volumetric flow rates into two rivers, A and B.
% loading rainfall
load('Monthly_Rainfall')   % rainfall data
 vrainfall = rainfall_perMo; 
%  loading water needs
load('Water_Needs') %water needs data for last 3 years
vcity = Vcity_perMo_3years; 
vfactory = Vfac_perMo_3years;
vfarm = Vfarm_perMo_3years;
rainfall = vrainfall;
% yearly water needs
city = mean(vcity);
factory = mean(vfactory);
farm = mean(vfarm);
m= 1:12;
% m = months
% plotting rainfall, waterneeds vs months
plot(m,rainfall,'b');
hold on
plot(m,city, 'k');
hold on
plot(m,factory, 'r');
hold on
plot(m,farm,'m');
legend ('Rainfall rate','City needs','Factory needs','Farm needs')
xlabel('months');
ylabel('flow rate in L/mo') 
title('Monthly Rainfall rate and Water needs')
set(gca,'XTick',[1:12]) 
months = ['Jan';'Feb';'Mar';'Apr';'May';'Jun';'Jul';'Aug';'Sep';'Oct';'Nov';'Dec'];
set(gca,'XTickLabel',months)
xlim([0 13])
grid on
% the graph represents 
%Seasons
winter = m(1:3);
spring = m(4:6);
summer = m(7:9);
fall =   m(10:12);
% Part2:  
% seasonal averages of rainfall
soilrunoff = 11.5*10^6;
% soilrunoff = soil run off factor(L/mo)
% vamax = Dam A maximum flow rate in L/mo
% vbmax = Dam B maximum flow rate in L/mo
vamax = 150e7;
vbmax = 180e7;
%  n = number of values
n=150;
vap =linspace(0,vamax,n);
vbp =linspace(0,vbmax,n);
%  net = net volume flowrate into the lake
 % Edama = electricity generatd in dam a in (M*W-hr)/(L) 
Edama = 13.20*10^(-3);
%Edamb = electricity generatd in dam b in (M*W-hr)/(L)
Edamb = 16.40*10^(-3);
% Pdam = Power generated by river A and B 
% Pneeds = Power needed seasonally in MW*hr/month
Pneeds = [2000 800 1050 950];
% 1 = winter
% if winter, all the calculations related to winter are put here
%%
if season == 1
winterrainfall =mean(vrainfall(winter));    
wintercity=mean(vcity(winter));% seasonal averages of water needs for City
winterfactory=mean(vfactory(winter));% seasonal averages of water needs for Factory
winterfarm=mean(vfarm(winter));% seasonal averages of water needs for Farm
facpollwinter  = 1E6-log(winterfactory);% facpollwinter = winter flow rate of the pollution into River B (season's in L/mo)
% farmpollwinter = winter flow rate of the polltion into river A(season's average in L/mo) 
farmpollwinter = winterrainfall*(1-winterrainfall/(winterrainfall+soilrunoff));
%  vmina = flow rate minimum for river a
%  vminb = flow rate minimum for river b
vmina = farmpollwinter*(1/0.01-1)+winterfarm;
vminb = facpollwinter*(1/0.004-1)+(winterfactory)+(wintercity);
% netminab = the minimum flow to the lake
 netminab = (vmina+vminb)-(winterfarm+winterfactory+wintercity)+(farmpollwinter+facpollwinter);
 net1 = zeros(length(vap),length(vbp));% net1= initial zero vectors 
% 2-d vector generation
% vneta = net flow rate of river a in L/mo
% vnetb = net flow rate of river b in L/mo
% Pdam = power generated by dam MW*hr
 for i = 1:length(vap)
      for j = 1: length(vbp)
       vneta(i) = (winterrainfall+vap(i)+farmpollwinter)-winterfarm;
       vnetb(j) = vbp(j)+facpollwinter-(winterfactory+wintercity);
        
          net(i,j) = vneta(i)+vnetb(j);
          
       Pdam(i,j) = Edama*(sqrt((vamax)^2-(vap(i)-vamax)^2))+ Edamb*(sqrt((vbmax)^2-(vbp(j)-vbmax)^2));
      end 
 end
 %  maxthing = maximum total flow rate in L/mo
       maxthing = 170e7;
       c1 = net<maxthing;%        c1 = condition 1: The lake can take a maximum total flow rate of  maxthing
       c2 = net>netminab;%        c1 = condition 2: greater than The minimum flow to the lake
       c3 = Pdam>Pneeds(1);%      c1 = condition 3: greater than power needs by a season       
      net12 = net.*(c1&c2); % net 12 = flow rate satisfying c1 and c2
      Pdam3  = Pdam.*(c3);% Pdam3 = Power satisfying c3
      net123 = net.*(c1&c2&c3); % net 123 = flow rate satisfying c1, c2, and c3
      Pdam123 = Pdam.*(c1&c2&c3);% Pdam3 = Power satisfying c1, c2, and c3     
%       plotting of 4 graphs 
% The first two are the clipped net flow into the lake, a surface which satisfies conditions 1 and 2, and the clipped net power generated surface which satisfies condition 3.
 figure
 subplot(2,2,1)     
 surf(vap,vbp,net12)
 xlabel('flow rate river A in L/mo')
 ylabel ('flow rate river Bin L/mo')
 zlabel ('acceptable flow rate in L/mo')
 title('acceptable flow rate under condition 1&2')
 subplot(2,2,2)
  surf(vap,vbp,Pdam3)
   xlabel('flow rate river A in L/mo')
 ylabel ('flow rate river B in L/mo')
 zlabel ('acceptable Power in MW ')
 title('acceptable Power under condition 3')
% The last two are the clipped net lake flow and net power generated, both satisfying all three conditions.  
 subplot(2,2,3)
  surf(vap,vbp,net123)
    xlabel('flow rate river A in L/mo')
 ylabel ('flow rate river B in L/mo')
 zlabel ('acceptable flow rate in L/mo')
 title('acceptable flow rate under condition 1&2&3')
 subplot(2,2,4)
  surf(vap,vbp,Pdam123)
  xlabel('flow rate river A in L/mo')
 ylabel ('flow rate river B in L/mo')
 zlabel ('acceptable Power in MW')
 title('acceptable Power under condition 123')       
% The corresponding refined (clipped)Dam A and B allowed flow rates should be displayed
[row1,column1] = find(net12);% finding rows and columns where the total flow satisfies c1&2
corrflow1 = [row1,column1]; %corrflow1 = row & column # of the flow rates of River A and B under c1&c2
corrflowA1=vneta(row1);    % flow rates of River A under c1&c2
corrflowB1=vnetb(column1); % flow rates of River B under c1&c2
corrflowAB1 = [corrflowA1, corrflowB1]; %the vector of flow rates of River A and B under c1&c2

[row2,column2] = find(net123);% finding rows and columns where the total flow satisfies c1&2&3
corrflow2 = [row2,column2];%corrflow2 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA2=vneta(row2);    %flow rates of River A under c1&c2&c3
corrflowB2=vnetb(column2); %flow rates of River B under c1&c2&c3
corrflowAB2 = [corrflowA2, corrflowB2]; %the vector of flow rates of River A and B under c1&2&3


[row3,column3] = find(Pdam3);% finding rows and columns where the total power satisfies c3
corrflow3 = [row3,column3];%corrflow3 = row & column # of the flow rates of River A and B under c3
corrflowA3=vneta(row3);% flow rates of River A under c3
corrflowB3=vnetb(column3);% flow rates of River B under c3
corrflowAB3 = [corrflowA3, corrflowB3];  %the vector of flow rates of River A and B under c3

[row4,column4] = find(Pdam123);% finding rows and columns where the total power satisfies c1&c2&c3
corrflow4 = [row4,column4];%corrflow4 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA4=vneta(row4);% flow rates of River A under c1&c2&c3
corrflowB4=vnetb(column4);% flow rates of River B under  c1&c2&c3
corrflowAB4 = [corrflowA4, corrflowB4];  %the vector of flow rates of River A and B under c1&c2&c3

%  plotting of possible Dam Flow rates
 figure
 subplot(1,2,1) 
 surf(vap,vbp,net)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('net volume flow rate into the lake((L/mo))')
 title('Possible Dam Flow Rates')
 %  plotting of possible Power 
subplot(1,2,2)
 surf(vap,vbp,Pdam)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('Power generated by river A and B in MW)')
 title('Possible Power generated by Dams')
      % maxpower = maximum power the City can generate
maxpower = max(max(Pdam123));
 [row,column] = find(Pdam123==maxpower); % row and column when Power generated is equvalent to the max
corrvector = [row,column];   %corrvector = row # and column # vector
x_max = row; %x_max = row of flow rate A when power is max
y_max = column;% y_max = column of flow rate B when power is max
corrflowA5=vneta(row); % flow rate A when power is max
corrflowB5=vnetb(column); %flow rate B when power is max
corrflowAB = [corrflowA5,corrflowB5]; % a point of flowrate A and B when power is max
% Pneeds is a vector of seasons
% Question: use of maxpower should be discussed more
powerremaining=maxpower-Pneeds(1);
% revenue = revenue then be generated per season
revenue =  powerremaining*0.05*1000*3;
% if spring, all the calculations related to spring are put here
%%2 = spring
else if season == 2
springrainfall=mean(vrainfall(spring));
springcity=mean(vcity(spring));% seasonal averages of water needs for City
springfactory=mean(vfactory(spring));% seasonal averages of water needs for Factory
springfarm=mean(vfarm(spring));% seasonal averages of water needs for Farm
facpollspring  = 1E6-log(springfactory);% facpollspring =spring flow rate of the pollution into River B (season's in L/mo)
% farmpollspring = spring flow rate of the polltion into river A(season's average in L/mo) 
farmpollspring = springrainfall*(1-springrainfall/(springrainfall+soilrunoff));
%  vmina = flow rate minimum for river a
%  vminb = flow rate minimum for river b
vmina = farmpollspring*(1/0.01-1)+springfarm;
vminb = facpollspring*(1/0.004-1)+[(springfactory)+(springcity)];
% netminab = the minimum flow to the lake
 netminab = (vmina+vminb)-(springfarm+springfactory+springcity)+(farmpollspring+facpollspring);
 net1 = zeros(length(vap),length(vbp));% net1= initial zero vectors 
% 2-d vector generation
% vneta = net flow rate of river a in L/mo
% vnetb = net flow rate of river b in L/mo
% Pdam = power generated by dam MW*hr
 for i = 1:length(vap)
      for j = 1: length(vbp)
       vneta(i) = (springrainfall+vap(i)+farmpollspring)-springfarm;
       vnetb(j) = vbp(j)+facpollspring-(springfactory+springcity);
          
          net(i,j) = vneta(i)+vnetb(j);
          
       Pdam(i,j) = Edama*(sqrt((vamax)^2-(vap(i)-vamax)^2))+ Edamb*(sqrt((vbmax)^2-(vbp(j)-vbmax)^2));
      end
 end
 %  maxthing = maximum total flow rate in L/mo
       maxthing = 170e7;
       c1 = net<maxthing;%        c1 = condition 1: The lake can take a maximum total flow rate of  maxthing
       c2 = net>netminab;%        c1 = condition 2: greater than The minimum flow to the lake
       c3 = Pdam>Pneeds(2);%      c1 = condition 3: greater than power needs by a season
      net12 = net.*(c1&c2); % net 12 = flow rate satisfying c1 and c2
      Pdam3  = Pdam.*(c3);% Pdam3 = Power satisfying c3
      net123 = net.*(c1&c2&c3); % net 123 = flow rate satisfying c1, c2, and c3
      Pdam123 = Pdam.*(c1&c2&c3);% Pdam3 = Power satisfying c1, c2, and c3
%       plotting of 4 graphs 
% The first two are the clipped net flow into the lake, a surface which satisfies conditions 1 and 2, and the clipped net power generated surface which satisfies condition 3.
 figure
 subplot(2,2,1)     
 surf(vap,vbp,net12)
 xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2') 
 subplot(2,2,2)
  surf(vap,vbp,Pdam3)
   xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 3')
% The last two are the clipped net lake flow and net power generated, both satisfying all three conditions.  
 subplot(2,2,3)
  surf(vap,vbp,net123)
    xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2&3')
 subplot(2,2,4)
  surf(vap,vbp,Pdam123)
  xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 123')       
%  plotting of possible Dam Flow rates
 figure
 subplot(1,2,1) 
 surf(vap,vbp,net)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('net volume flow rate into the lake((L/mo))')
 title('Possible Dam Flow Rates')
 %  plotting of possible Power 
subplot(1,2,2)
 surf(vap,vbp,Pdam)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('Power generated by river A and B )')
 title('Possible Power generated by Dams')
 % The corresponding refined (clipped)Dam A and B allowed flow rates should be displayed
 [row1,column1] = find(net12);% finding rows and columns where the total flow satisfies c1&2
corrflow1 = [row1,column1]; %corrflow1 = row & column # of the flow rates of River A and B under c1&c2
corrflowA1=vneta(row1);    % flow rates of River A under c1&c2
corrflowB1=vnetb(column1); % flow rates of River B under c1&c2
corrflowAB1 = [corrflowA1, corrflowB1]; %the vector of flow rates of River A and B under c1&c2

[row2,column2] = find(net123);% finding rows and columns where the total flow satisfies c1&2&3
corrflow2 = [row2,column2];%corrflow2 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA2=vneta(row2);    %flow rates of River A under c1&c2&c3
corrflowB2=vnetb(column2); %flow rates of River B under c1&c2&c3
corrflowAB2 = [corrflowA2, corrflowB2]; %the vector of flow rates of River A and B under c1&2&3


[row3,column3] = find(Pdam3);% finding rows and columns where the total power satisfies c3
corrflow3 = [row3,column3];%corrflow3 = row & column # of the flow rates of River A and B under c3
corrflowA3=vneta(row3);% flow rates of River A under c3
corrflowB3=vnetb(column3);% flow rates of River B under c3
corrflowAB3 = [corrflowA3, corrflowB3];  %the vector of flow rates of River A and B under c3

[row4,column4] = find(Pdam123);% finding rows and columns where the total power satisfies c1&c2&c3
corrflow4 = [row4,column4];%corrflow4 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA4=vneta(row4);% flow rates of River A under c1&c2&c3
corrflowB4=vnetb(column4);% flow rates of River B under  c1&c2&c3
corrflowAB4 = [corrflowA4, corrflowB4];  %the vector of flow rates of River A and B under c1&c2&c3
 % maxpower = maximum power the City can generate
maxpower = max(max(Pdam123));
[row,column] = find(Pdam123==maxpower);
corrvector = [row,column];   %corrvector = row and column vector
x_max = row; %x_max = row of flow rate A when power is max
y_max = column;% y_max = column of flow rate B when power is max
corrflowA5=vneta(row); % flow rate A when power is max
corrflowB5=vnetb(column); %flow rate B when power is max
corrflowAB = [corrflowA5,corrflowB5]; % a point of flowrate A and B when power is max
% Pneeds is a vector of seasons
% Question: use of maxpower should be discussed more
powerremaining=maxpower-Pneeds(2);
% revenue = revenue then be generated per season
revenue =  powerremaining*0.05*1000*3;
% if summer, all the calculations related to summer are put here
%% summer =3
else if season == 3
summerrainfall=mean(vrainfall(summer));
summercity=mean(vcity(summer));% seasonal averages of water needs for City
summerfactory=mean(vfactory(summer));% seasonal averages of water needs for Factory
summerfarm=mean(vfarm(summer));% seasonal averages of water needs for Farm
% farmpollsummer = summer flow rate of the polltion into river A(season's average in L/mo) 
% Korede changes
% farmpollsummer = summerrainfall*(1-summerrainfall/(summerrainfall+soilrunoff));
farmpollsummer = summerrainfall*(1-summerrainfall/(summerrainfall+soilrunoff));
facpollsummer = 1E6-log(summerfactory);% facpollsummer =summer flow rate of the pollution into River B (season's in L/mo)
%  vmina = flow rate minimum for river a
%  vminb = flow rate minimum for river b
vmina = farmpollsummer*(1/0.01-1)+summerfarm;
vminb = facpollsummer*(1/0.004-1)+[(summerfactory)+(summercity)];
% netminab = the minimum flow to the lake
 netminab = (vmina+vminb)-(summerfarm+summerfactory+summercity)+(farmpollsummer+facpollsummer);
 net1 = zeros(length(vap),length(vbp));% net1= initial zero vectors 
% 2-d vector generation
% vneta = net flow rate of river a in L/mo
% vnetb = net flow rate of river b in L/mo
% Pdam = power generated by dam MW*hr
 for i = 1:length(vap)
      for j = 1: length(vbp)
       vneta(i) = (summerrainfall+vap(i)+farmpollsummer)-summerfarm;
       vnetb(j) = vbp(j)+facpollsummer-(summerfactory+summercity);
          
          net(i,j) = vneta(i)+vnetb(j);
          
       Pdam(i,j) = Edama*(sqrt((vamax)^2-(vap(i)-vamax)^2))+ Edamb*(sqrt((vbmax)^2-(vbp(j)-vbmax)^2));
      end
 end
 %  maxthing = maximum total flow rate in L/mo
       maxthing = 170e7;
       c1 = net<maxthing;%        c1 = condition 1: The lake can take a maximum total flow rate of  maxthing
       c2 = net>netminab;%        c1 = condition 2: greater than The minimum flow to the lake
       c3 = Pdam>Pneeds(3);%      c1 = condition 3: greater than power needs by a season      
      net12 = net.*(c1&c2); % net 12 = flow rate satisfying c1 and c2
      Pdam3  = Pdam.*(c3);% Pdam3 = Power satisfying c3
      net123 = net.*(c1&c2&c3); % net 123 = flow rate satisfying c1, c2, and c3
      Pdam123 = Pdam.*(c1&c2&c3);% Pdam3 = Power satisfying c1, c2, and c3      
%       plotting of 4 graphs 
% The first two are the clipped net flow into the lake, a surface which satisfies conditions 1 and 2, and the clipped net power generated surface which satisfies condition 3.
 figure
 subplot(2,2,1)     
 surf(vap,vbp,net12)
 xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2')
 subplot(2,2,2)
  surf(vap,vbp,Pdam3)
   xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 3')
% The last two are the clipped net lake flow and net power generated, both satisfying all three conditions.  
 subplot(2,2,3)
  surf(vap,vbp,net123)
    xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2&3')
 subplot(2,2,4)
  surf(vap,vbp,Pdam123)
  xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 123')       
%  plotting of possible Dam Flow rates
 figure
 subplot(1,2,1) 
 surf(vap,vbp,net)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('net volume flow rate into the lake((L/mo))')
 title('Possible Dam Flow Rates')
 %  plotting of possible Power 
subplot(1,2,2)
 surf(vap,vbp,Pdam)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('Power generated by river A and B )')
 title('Possible Power generated by Dams')
% The corresponding refined (clipped)Dam A and B allowed flow rates should be displayed
 [row1,column1] = find(net12);% finding rows and columns where the total flow satisfies c1&2
corrflow1 = [row1,column1]; %corrflow1 = row & column # of the flow rates of River A and B under c1&c2
corrflowA1=vneta(row1);    % flow rates of River A under c1&c2
corrflowB1=vnetb(column1); % flow rates of River B under c1&c2
corrflowAB1 = [corrflowA1, corrflowB1]; %the vector of flow rates of River A and B under c1&c2

[row2,column2] = find(net123);% finding rows and columns where the total flow satisfies c1&2&3
corrflow2 = [row2,column2];%corrflow2 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA2=vneta(row2);    %flow rates of River A under c1&c2&c3
corrflowB2=vnetb(column2); %flow rates of River B under c1&c2&c3
corrflowAB2 = [corrflowA2, corrflowB2]; %the vector of flow rates of River A and B under c1&2&3


[row3,column3] = find(Pdam3);% finding rows and columns where the total power satisfies c3
corrflow3 = [row3,column3];%corrflow3 = row & column # of the flow rates of River A and B under c3
corrflowA3=vneta(row3);% flow rates of River A under c3
corrflowB3=vnetb(column3);% flow rates of River B under c3
corrflowAB3 = [corrflowA3, corrflowB3];  %the vector of flow rates of River A and B under c3

[row4,column4] = find(Pdam123);% finding rows and columns where the total power satisfies c1&c2&c3
corrflow4 = [row4,column4];%corrflow4 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA4=vneta(row4);% flow rates of River A under c1&c2&c3
corrflowB4=vnetb(column4);% flow rates of River B under  c1&c2&c3
corrflowAB4 = [corrflowA4, corrflowB4];  %the vector of flow rates of River A and B under c1&c2&c3
 % maxpower = maximum power the City can generate
maxpower = max(max(Pdam123));
[row,column] = find(Pdam123==maxpower);
corrvector = [row,column];   %corrvector = row and column vector
x_max = row; %x_max = row of flow rate A when power is max
y_max = column;% y_max = column of flow rate B when power is max
corrflowA5=vneta(row); % flow rate A when power is max
corrflowB5=vnetb(column); %flow rate B when power is max
corrflowAB = [corrflowA5,corrflowB5]; % a point of flowrate A and B when power is max
% Pneeds is a vector of seasons
% Question: use of maxpower should be discussed more
powerremaining=maxpower-Pneeds(3);
% revenue = revenue then be generated per season
revenue =  powerremaining*0.05*1000*3;    
% if fall, all the calculations related to fall are put here
%% fall = 4 
else if season == 4
fallrainfall=mean(vrainfall(fall));
fallcity=mean(vcity(fall));% seasonal averages of water needs for City
fallfactory=mean(vfactory(fall));% seasonal averages of water needs for Factory
fallfarm=mean(vfarm(fall));% seasonal averages of water needs for Farm
% farmpollfall = fall flow rate of the polltion into river A(season's average) 
farmpollfall = fallrainfall*(1-fallrainfall/(fallrainfall+soilrunoff));
facpollfall  = 1E6-log(fallfactory);% facpollfall =fall flow rate of the pollution into River B (season's in L/mo)
%  vmina = flow rate minimum for river a
%  vminb = flow rate minimum for river b
vmina = farmpollfall*(1/0.01-1)+fallfarm;
vminb = facpollfall*(1/0.004-1)+(fallfactory)+(fallcity);
% netminab = the minimum flow to the lake
 netminab = (vmina+vminb)-(fallfarm+fallfactory+fallcity)+(farmpollfall+facpollfall);
 net1 = zeros(length(vap),length(vbp));% net1= initial zero vectors 
% 2-d vector generation
% vneta = net flow rate of river a in L/mo
% vnetb = net flow rate of river b in L/mo
% Pdam = power generated by dam MW*hr
 for i = 1:length(vap)
      for j = 1: length(vbp)
       vneta(i) = (fallrainfall+vap(i)+farmpollfall)-fallfarm;
       vnetb(j) = vbp(j)+facpollfall-(fallfactory+fallcity);
          
          net(i,j) = vneta(i)+vnetb(j);
          
       Pdam(i,j) = Edama*(sqrt((vamax)^2-(vap(i)-vamax)^2))+ Edamb*(sqrt((vbmax)^2-(vbp(j)-vbmax)^2));
      end      
 end
 %  maxthing = maximum total flow rate in L/mo
       maxthing = 170e7;
       c1 = net<maxthing;%        c1 = condition 1: The lake can take a maximum total flow rate of  maxthing
       c2 = net>netminab;%        c1 = condition 2: greater than The minimum flow to the lake
       c3 = Pdam>Pneeds(4);%      c1 = condition 3: greater than power needs by a season       
      net12 = net.*(c1&c2); % net 12 = flow rate satisfying c1 and c2
      Pdam3  = Pdam.*(c3);% Pdam3 = Power satisfying c3
      net123 = net.*(c1&c2&c3); % net 123 = flow rate satisfying c1, c2, and c3
      Pdam123 = Pdam.*(c1&c2&c3);% Pdam3 = Power satisfying c1, c2, and c3
%       plotting of 4 graphs 
% The first two are the clipped net flow into the lake, a surface which satisfies conditions 1 and 2, and the clipped net power generated surface which satisfies condition 3.
 figure
 subplot(2,2,1)     
 surf(vap,vbp,net12) 
 xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2')
 subplot(2,2,2)
  surf(vap,vbp,Pdam3)
   xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 3')
% The last two are the clipped net lake flow and net power generated, both satisfying all three conditions.  
 subplot(2,2,3)
  surf(vap,vbp,net123)
    xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable flow rate ')
 title('acceptable flow rate under condition 1&2&3')
 subplot(2,2,4)
  surf(vap,vbp,Pdam123)
  xlabel('flow rate river A')
 ylabel ('flow rate river B')
 zlabel ('acceptable Power ')
 title('acceptable Power under condition 123')       
%  plotting of possible Dam Flow rates
 figure
 subplot(1,2,1) 
 surf(vap,vbp,net)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('net volume flow rate into the lake((L/mo))')
 title('Possible Dam Flow Rates')
 %  plotting of possible Power 
subplot(1,2,2)
 surf(vap,vbp,Pdam)
 xlabel('Dam A flow rate(L/mo)')
 ylabel('Dam B flow rate(L/mo)')
 zlabel('Power generated by river A and B )')
 title('Possible Power generated by Dams')
   % The corresponding refined (clipped)Dam A and B allowed flow rates should be displayed
 [row1,column1] = find(net12);% finding rows and columns where the total flow satisfies c1&2
corrflow1 = [row1,column1]; %corrflow1 = row & column # of the flow rates of River A and B under c1&c2
corrflowA1=vneta(row1);    % flow rates of River A under c1&c2
corrflowB1=vnetb(column1); % flow rates of River B under c1&c2
corrflowAB1 = [corrflowA1, corrflowB1]; %the vector of flow rates of River A and B under c1&c2

[row2,column2] = find(net123);% finding rows and columns where the total flow satisfies c1&2&3
corrflow2 = [row2,column2];%corrflow2 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA2=vneta(row2);    %flow rates of River A under c1&c2&c3
corrflowB2=vnetb(column2); %flow rates of River B under c1&c2&c3
corrflowAB2 = [corrflowA2, corrflowB2]; %the vector of flow rates of River A and B under c1&2&3


[row3,column3] = find(Pdam3);% finding rows and columns where the total power satisfies c3
corrflow3 = [row3,column3];%corrflow3 = row & column # of the flow rates of River A and B under c3
corrflowA3=vneta(row3);% flow rates of River A under c3
corrflowB3=vnetb(column3);% flow rates of River B under c3
corrflowAB3 = [corrflowA3, corrflowB3];  %the vector of flow rates of River A and B under c3

[row4,column4] = find(Pdam123);% finding rows and columns where the total power satisfies c1&c2&c3
corrflow4 = [row4,column4];%corrflow4 = row & column # of the flow rates of River A and B under c1&c2&c3
corrflowA4=vneta(row4);% flow rates of River A under c1&c2&c3
corrflowB4=vnetb(column4);% flow rates of River B under  c1&c2&c3
corrflowAB4 = [corrflowA4, corrflowB4];  %the vector of flow rates of River A and B under c1&c2&c3
 
 % maxpower = maximum power the City can generate  
maxpower = max(max(Pdam123));
[row,column] = find(Pdam123==maxpower);
corrvector = [row,column];   %corrvector = row and column vector
x_max = row; %x_max = row of flow rate A when power is max
y_max = column;% y_max = column of flow rate B when power is max
corrflowA5=vneta(row); % flow rate A when power is max
corrflowB5=vnetb(column); %flow rate B when power is max
corrflowAB = [corrflowA5,corrflowB5]; % a point of flowrate A and B when power is max
% Pneeds is a vector of seasons
% Question: use of maxpower should be discussed more
powerremaining=maxpower-Pneeds(4);
% revenue = revenue then be generated per season
revenue =  powerremaining*0.05*1000*3; 

    end
    end
    end
end
end
